version: '3.4'

services:
  kernel:
    build: secondo
    ports:
      - 1234:1234
    volumes:
      - "secondo_data:/home/secondo/secondo_data"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1234"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 5s

  optimizer:
    build: secondo
    command: ./start-optimizer
    depends_on:
      - kernel
    environment:
      - SECONDO_HOST=kernel
      - SECONDO_PORT=1234
    ports:
      - 1235:1235

volumes:
  secondo_data:
