version: '3'

services:
  kernel:
    build: secondo
    ports:
      - "1234:1234"
    volumes:
      - "secondo_data:/home/secondo/secondo_data"

  optimizer:
    build: secondo
    command: ./start-optimizer
    environment:
      - "SECONDO_HOST=kernel"
      - "SECONDO_PORT=1234"
    ports:
      - "1235:1235"

volumes:
  secondo_data:
