version: '3.4'

services:
  kernel:
    build: .
    image: nieltg/secondo:v412-LAT1
    ports:
      - 1234:1234
    volumes:
      - "secondo_data:/home/secondo/secondo-databases"
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "1234"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 5s

  optimizer:
    build: .
    image: nieltg/secondo:v412-LAT1
    command: ["./start-optimizer"]
    depends_on:
      - kernel
    environment:
      - SECONDO_HOST=kernel
      - SECONDO_PORT=1234
    ports:
      - 1235:1235
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "1235"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 5s

volumes:
  secondo_data:
